sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"
  - LARAVEL_VERSION="5.3.*"
  - LARAVEL_VERSION="5.4.*"

before_script:
  - composer self-update
  - composer require laravel/framework:$LARAVEL_VERSION --no-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter
